//用户地址操作

export const INIT_USER_ADD_LIST = 'INIT_USER_ADD_LIST';
export const SET_DEFAULT_ADDRESS = 'SET_DEFAULT_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';

export const UPDATE_TMP_USER_ADDRESS = 'UPDATE_TMP_USER_ADDRESS';
export const INIT_TMP_USER_ADDRESS = 'INIT_TMP_USER_ADDRESS';
export const RESET_TMP_USER_ADDRESS = 'RESET_TMP_USER_ADDRESS';
export const ADD_USER_ADDRESS = 'ADD_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS'
