//首页主题查询
export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST';
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS';
export const SUBJECT_LIST_FAILURE = 'SUBJECT_LIST_FAILURE';
export const SUBJECT_LIST_CLEAR = 'SUBJECT_LIST_CLEAR';

//分类信息
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAILURE = 'CATEGORY_LIST_FAILURE';

//商品列表
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE';
export const PRODUCT_LIST_CLEAR = 'PRODUCT_LIST_CLEAR';

//商品详情
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';
export const PRODUCT_CLEAR = 'PRODUCT_CLEAR';

//切换tab:"人气、新品、价格、筛选"
export const SWITCH_TAB = 'SWITCH_TAB';
//价格排序
export const PRICE_ORDER = 'PRICE_ORDER';

//商品列表已选中的商品
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
//清空选中的商品
export const CLEAR_SELECT_PRODUCT = 'CLEAR_SELECT_PRODUCT';
