//红包参与人列表
export const PARTICIPANTS_REQUEST = 'PARTICIPANTS_REQUEST';
export const PARTICIPANTS_SUCCESS = 'PARTICIPANTS_SUCCESS';
export const PARTICIPANTS_FAILURE = 'PARTICIPANTS_FAILURE';
export const PARTICIPANTS_CLEAR = 'PARTICIPANTS_CLEAR';

//红包详情
export const HONGBAO_DETAIL_REQUEST = 'HONGBAO_DETAIL_REQUEST';
export const HONGBAO_DETAIL_SUCCESS = 'HONGBAO_DETAIL_SUCCESS';
export const HONGBAO_DETAIL_FAILURE = 'HONGBAO_DETAIL_FAILURE';
export const HONGBAO_DETAIL_CLEAR = 'HONGBAO_DETAIL_CLEAR';
