//我发起的红包
export const SPONSOR_REQUEST = 'SPONSOR_REQUEST';
export const SPONSOR_SUCCESS = 'SPONSOR_SUCCESS';
export const SPONSOR_FAILURE = 'SPONSOR_FAILURE';
export const SPONSOR_CLEAR = 'SPONSOR_CLEAR';

//我收到的红包
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';
export const RECEIVE_SUCCESS = 'RECEIVE_SUCCESS';
export const RECEIVE_FAILURE = 'RECEIVE_FAILURE';
export const RECEIVE_CLEAR = 'RECEIVE_CLEAR';

//用户信息
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';

